# Self-attention study

## Simple self-attention

In [1]:
import torch

In [2]:
inputs = torch.tensor(
 [[0.43, 0.15, 0.89], # Your (x^1)
 [0.55, 0.87, 0.66], # journey (x^2)
 [0.57, 0.85, 0.64], # starts (x^3)
 [0.22, 0.58, 0.33], # with (x^4)
 [0.77, 0.25, 0.10], # one (x^5)
 [0.05, 0.80, 0.55]] # step (x^6)
)

In [4]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [5]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print('Attention weights: ', attn_weights_2)
print('Attention weights sum: ', attn_weights_2.sum())

Attention weights:  tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Attention weights sum:  tensor(1.)


In [8]:
contex_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    contex_vec_2 += attn_weights_2[i] * x_i
print(contex_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [9]:
attn_weights = inputs @ inputs.T
attn_weights = torch.softmax(attn_weights, dim=-1)

In [10]:
all_contex_vec = attn_weights @ inputs

In [11]:
all_contex_vec

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

## Self-attention with weights 

In [82]:
x_2 = inputs[1]
in_dim = inputs.shape[1]
out_dim = 2 

In [83]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(in_dim, out_dim), requires_grad=False)
W_keys = torch.nn.Parameter(torch.rand(in_dim, out_dim), requires_grad=False)
W_values = torch.nn.Parameter(torch.rand(in_dim, out_dim), requires_grad=False)

In [84]:
query_2 = x_2 @ W_query
keys = inputs @ W_keys
values = inputs @ W_values

In [92]:
attn_scores_2 = query_2 @ keys.T
attn_weights_2 = torch.softmax(attn_scores_2/keys.shape[-1]**0.5, dim=-1)

In [93]:
contex_vec_2 = attn_weights_2 @ values

In [94]:
contex_vec_2

tensor([0.3061, 0.8210])

In [88]:
import torch.nn as nn

In [101]:
class SelfAttention_v1(nn.Module): 

    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_keys = nn.Parameter(torch.rand(d_in, d_out))
        self.W_values = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
        queries = x @ self.W_query
        keys = x @ self.W_keys
        values = x @ self.W_values

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)

        contex_vec = attn_weights @ values
        return contex_vec

In [102]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(inputs.shape[1], out_dim)

In [103]:
sa_v1(inputs)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)

In [104]:
class SelfAttention_v2(nn.Module): 

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_keys =  nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_values =  nn.Linear(d_in, d_out, bias = qkv_bias)

    def forward(self, x):
        queries = self.W_query(x) 
        keys = self.W_keys(x)
        values = self.W_values(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim=-1)

        contex_vec = attn_weights @ values
        return contex_vec

In [107]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(inputs.shape[1], out_dim)

In [108]:
sa_v2(inputs)

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)

In [124]:
sa_v1(inputs)

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)

In [123]:
sa_v1.W_query.data.copy_(sa_v2.W_query.weight.T)
sa_v1.W_keys.data.copy_(sa_v2.W_keys.weight.T)
sa_v1.W_values.data.copy_(sa_v2.W_values.weight.T)

tensor([[ 0.2526,  0.5191],
        [-0.1415, -0.0852],
        [-0.1962, -0.2043]], grad_fn=<CopyBackwards>)