# Self-attention study

## Simple self-attention

In [1]:
import torch

In [2]:
inputs = torch.tensor(
 [[0.43, 0.15, 0.89], # Your (x^1)
 [0.55, 0.87, 0.66], # journey (x^2)
 [0.57, 0.85, 0.64], # starts (x^3)
 [0.22, 0.58, 0.33], # with (x^4)
 [0.77, 0.25, 0.10], # one (x^5)
 [0.05, 0.80, 0.55]] # step (x^6)
)

In [12]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attention_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [17]:
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print('Attention weights: ', attn_weights_2)
print('Attention weights sum: ', attn_weights_2.sum())

Attention weights:  tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Attention weights sum:  tensor(1.)


In [34]:
contex_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    contex_vec_2 += attn_weights_2[i] * x_i
print(context_vec_2)

tensor([0.4419, 0.6515, 0.5683])


In [39]:
attn_weights = inputs @ inputs.T
attn_weights = torch.softmax(attn_weights, dim=-1)

In [42]:
all_contex_vec = attn_weights @ inputs

In [43]:
all_contex_vec

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])

## Self-attention with weights 